#!/bin/bash
echo Building React App...
cd front-end 
echo Entered in frontend folder running npm install now...
npm install 
echo npm install complete, running build now...
npm run build 
echo Build completed!
echo build complete, now copying the files to static backend folder...
cp dist/. -R ../back-end/src/main/resources/static
echo copy complete, now switching to backend folder...
cd ../back-end/
echo switched to backend folder, now building JAR file...
mvn clean install
echo build complete, JAR file can be found at back-end/target folder ...
