@echo off
echo Building React App...
cd front-end
echo Entered in frontend folder running npm install now...
call npm install
echo npm install complete, running build now...
call npm run build
echo Build completed!
echo build complete, now copying the files to static backend folder...
call xcopy "dist" "..\back-end\src\main\resources\static\" /E /Y /I
echo copy complete, now switching to backend folder...
cd ..\back-end
echo switched to backend folder, now building JAR file...
call mvn clean install
echo build complete, JAR file can be found at back-end/target folder ...
pause